### ISSUE TITLE
Stream with dxgi no output.

### ISSUE THREAD

**Issue by lozycve** [Kirides/screen-share#2]
I had ran the code on windows10 platform, but could not get any output on localhost:8023/watch after i build the code.
However i change the function of acquiring stream by using old Bltbit, then i got the video.
are there some bugs in calling  interface of dxgi?

**Comment by kirides** [comment]
work's on my amd notebook (3500u), an HP notebook (HP Elite, intel i5-1135G7) and my dekstop with an Nvidia RTX 2080.
all on latest windows 10 21H1...

tried with a simple
```bash
> go run .
```
and opened a webbrowser on `http://127.0.0.1:8023/watch?screen=0`

**Comment by kirides** [comment]
On a separate note, there _might_ be issues if a you have multiple graphics cards and your monitors are connected using two different cards (e.g. integrated monitor from notebook and external monitor via HDMI powered by an Nvidia GPU)

But since i don't own such a system, debugging and fixing those issues won't be my priority.
